apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170901183
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170901183
    app.kubernetes.io/part-of: test-app-170901183
  name: java-quarkus-170901183
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170901183
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170901183
    spec:
      containers:
      - image: quay.io/hacdev/vi41v4ud-tenant/test-app-170901183/java-quarkus-170901183@sha256:71d2e68493a14586bef6edb0372ad0b5f894270db3c63698c257717b478567d2
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
